import { test, expect } from "@playwright/test";

test("mobile facility booking, failed-upload retry, incident and immutable lock-up history", async ({ page, context }) => {
  page.setDefaultTimeout(20000);
  const login = await context.request.post("/api/auth/sign-in/email", {
    headers: { origin: "http://127.0.0.1:3100" }, data: { email: "captain@example.test", password: process.env.E2E_PASSWORD! },
  });
  expect(login.ok()).toBe(true);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/facilities-management");
  await expect(page.getByRole("heading", { name: "Facilities Management", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Open navigation" }).click();
  const nav = page.getByRole("navigation", { name: "Main navigation" });
  const links = await nav.getByRole("link").allTextContents();
  expect(links[links.indexOf("Discussions") + 1]).toBe("Club Management");
  await nav.getByRole("link", { name: "Club Management" }).click();
  await page.getByText("Configure security checklists", { exact: true }).click();
  await page.getByLabel("Opening checklist", { exact: true }).fill("Access checked");
  await page.getByLabel("Lock-up checklist", { exact: true }).fill("Doors secured");
  await page.getByRole("button", { name: "Save checklists" }).click();
  await expect(page.getByRole("status").filter({ hasText: "Checklists saved" })).toBeVisible();
  await page.getByText("Add pitch booking", { exact: true }).click();
  await page.getByLabel("Facility / pitch", { exact: true }).fill("Test pitch");
  await expect(page.getByLabel("Session", { exact: true })).toHaveCount(0);
  await page.getByLabel("Booking team", { exact: true }).selectOption("firsts");
  await page.getByLabel("Responsible person", { exact: true }).selectOption({ label: "Test Captain" });
  const local = (date: Date) => new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
  await page.getByLabel("Starts", { exact: true }).fill(local(new Date(Date.now() - 3600000)));
  await page.getByLabel("Ends", { exact: true }).fill(local(new Date(Date.now() - 60000)));
  await page.getByRole("button", { name: "Create booking", exact: true }).click();
  await expect(page.getByRole("status").filter({ hasText: "Booking created" })).toBeVisible();
  const panel = page.getByRole("region", { name: "Booking security" });
  await expect(panel).toContainText("Lock-Up Outstanding");
  await panel.getByRole("button", { name: "Submit opening check" }).click();
  await expect(panel.getByRole("alert")).toContainText("Complete these items");
  const image = await page.screenshot();
  const photo = { name: "evidence.png", mimeType: "image/png", buffer: image };
  const opening = panel.locator("details").filter({ has: page.getByRole("heading", { name: "Opening check", exact: true }) });
  await opening.getByLabel("Upload facility photo", { exact: true }).setInputFiles(photo);
  await expect(opening.getByAltText("facility evidence preview")).toBeVisible();
  await opening.getByLabel("Upload pitch photo", { exact: true }).setInputFiles(photo);
  await expect(opening.getByAltText("pitch evidence preview")).toBeVisible();
  await opening.getByRole("button", { name: "Cannot confirm — report an issue" }).click();
  await opening.getByLabel("Issue description").fill("Door already open on arrival");
  await page.route("**/api/facility-security", async route => {
    if (route.request().method() === "POST") await route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: "Temporary upload failure. Please retry." }) });
    else await route.continue();
  }, { times: 1 });
  await opening.getByRole("button", { name: "Submit opening check" }).click();
  await expect(opening.getByRole("alert")).toContainText("Temporary upload failure");
  await expect(opening.getByLabel("Issue description")).toHaveValue("Door already open on arrival");
  await expect(opening.getByAltText("facility evidence preview")).toBeVisible();
  await opening.getByRole("button", { name: "Submit opening check" }).click();
  await expect(panel).toContainText("Opening check complete");
  await expect(panel).toContainText("Door already open on arrival");
  const closing = panel.locator("details").filter({ has: page.getByRole("heading", { name: "Lock-up check", exact: true }) });
  await closing.getByLabel("Upload facility photo", { exact: true }).setInputFiles(photo);
  await expect(closing.getByAltText("facility evidence preview")).toBeVisible();
  await closing.getByLabel("Upload pitch photo", { exact: true }).setInputFiles(photo);
  await expect(closing.getByAltText("pitch evidence preview")).toBeVisible();
  await closing.getByLabel("Doors secured", { exact: true }).check();
  await closing.getByRole("button", { name: "Submit lock-up check" }).click();
  await expect(panel).toContainText("Post-Check Complete");
  await expect(panel.getByRole("button", { name: "Submit lock-up check" })).toHaveCount(0);
  const evidenceLink = panel.getByRole("link", { name: "View facility photo" }).first();
  expect((await context.request.get((await evidenceLink.getAttribute("href"))!)).status()).toBe(200);
  await page.reload();
  await page.getByRole("button", { name: /Ladies 1s.*Test pitch/ }).click();
  await expect(panel).toContainText("Post-Check Complete");
  await expect(panel).toContainText("Door already open on arrival");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
